title: Site

tabs:
  # Pages
  home:
    label: Home
    icon: dashboard
    columns:
      published:
        width: 2/3
        sections:
          public:
            headline: Home
            type: pages
            layout: cards
            status: published
            flip: true
            image:
              cover: true
              ratio: 16/9
            templates: 
              - home

      home_drafts:
        width: 1/3
        sections:
          drafts:
            headline: Drafts
            type: pages
            layout: cardlets
            status: draft
            image:
              cover: true
              ratio: 16/9
            templates: 
              - home

  settings:
    label: Configuration
    icon: settings
    columns:
      content:
        type: fields
        width: 2/3
        fields:
          categories:
            label: Categories
            type: tags

          description:
            label: Descripción
            type: textarea

          footer:
            label: Footer Pages
            type: pages

      sidebar:
        sticky: true
        width: 1/3
        sections:
          files:
            headline: Files
            type: files

  menu:
    label: Menu
    icon: menu
    columns:
      izquierda:
        width: 2/3
        sections:
          clasicos:
            slug: clasicos
            headline: Clásicos Refrescantes
            type: pages
            layout: list
            templates:
              - clasicos
            status: all

          especiales:
            headline: Especiales de la Casa
            type: pages
            layout: list
            templates:
              - especiales

          frutal:
            headline: Frutal
            type: pages
            layout: list
            templates:
              - frutal
            status: all

          platillos:
            headline: Platillos para acompañar
            type: pages
            layout: list
            templates:
              - platillos
            status: all

          detox:
            headline: Funcionales & Detox
            type: pages
            layout: list
            templates:
              - detox
            status: all

      derecha:
        width: 1/3
        sections:
          imagenes:
            type: fields
            fields:
              imagen_especiales:
                label: Imagen de la sección “Especiales”
                type: files
                layout: cards
                max: 1
                width: 1/2
                image:
                  cover: true
                  ratio: 1/1

              imagen_frutal:
                label: Imagen de la sección “Frutal”
                type: files
                layout: cards
                max: 1
                width: 1/2
                image:
                  cover: true
                  ratio: 1/1

              imagen_platillos:
                label: Imagen de la sección “Platillos”
                type: files
                layout: cards
                max: 1
                width: 1/2
                image:
                  cover: true
                  ratio: 1/1

              imagen_clasicos:
                label: Imagen de la sección “Clásicos”
                type: files
                layout: cards
                max: 1
                width: 1/2
                image:
                  cover: true
                  ratio: 1/1

              imagen_detox:
                label: Imagen de la sección “Detox”
                type: files
                layout: cards
                max: 1
                width: 1/2
                image:
                  cover: true
                  ratio: 1/1

  seo:
    label: SEO
    icon: search
    columns:
      content:
        type: fields
        width: 2/3
        fields:
          meta_title:
            label: Meta Title
            type: text

