title: Site
tabs:
  # Pages
  home:
    label: Home
    icon: dashboard
    columns:
      published:
        width: 2/3
        sections:
          public:
            headline: Home
            type: pages
            layout: cards
            status: published
            flip: true
            image:
              cover: true
              ratio: 16/9
            templates: 
              - home

      home_drafts:
        width: 1/3
        sections:
          drafts:
            headline: Drafts
            type: pages
            layout: cardlets
            status: draft
            image:
              cover: true
              ratio: 16/9
            templates: 
              - home

  settings:
    label: Configuration
    icon: settings
    columns:
      content:
        type: fields
        width: 2/3
        fields:
          categories:
            label: Categories
            type: tags

          description:
            label: Descripción
            type: textarea

          footer:
            label: Footer Pages
            type: pages

      sidebar:
        sticky: true
        width: 1/3
        sections:
          files:
            headline: Files
            type: files

  menu:
    label: Menu
    icon: menu
    columns:
      first_column:
        width: 1/3
        sections:
          casa:
            headline: Especiales de la Casa
            type: pages
            layout: list
            templates:
              - casa

          otras_bebidas:
            headline: Otras Bebidas
            type: pages
            layout: list
            templates:
              - otras_bebidas
            status: all

      second_column:
        width: 1/3
        sections:
          platillos:
            headline: Platillos para acompañar
            type: pages
            layout: list
            templates:
              - platillos
            status: all

      third_column:
        width: 1/3
        sections:
          clasicos:
            headline: Clásicos Refrescantes
            type: pages
            layout: list
            templates:
              - clasicos
            status: all

          detox:
            headline: Funcionales & Detox
            type: pages
            layout: list
            templates:
              - detox
            status: all

  seo:
    label: SEO
    icon: search
    columns:
      content:
        type: fields
        width: 2/3
        fields:
          meta_title:
            label: Meta Title
            type: text
